rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
env:
  - RAILS_ENV=development CODECLIMATE_REPO_TOKEN=b2d573b4ad139331f307e536679084a8ec269d721e31b0afe81c503a7ab0c683
